[package]
name = "tetra_dungeon"
version = "0.1.0"
authors = ["Daniel <dhav211@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.6.5"
ldtk = { version = "0.4.1", features = ["ldtk-v0-9-3"] }